RequireFiles("Shared/Classes/", {
    "LocalSettings",
    "Favorites",
    "EasyCheat",
    "CheatManager",
    "CheatDefinitions",
    "Item",
    "ItemManager",
    "ItemPreview",
    "StatDefinitions",
    "StatPassiveManager",
    "StatSpellManager",
    "StatStatusManager",
    "TagManager",
    -- "TeleportManager",
})